// Pilot roster: each pilot has a distinct ship variant and capability profile.

export const PILOTS = [
  {
    id: "vega",
    name: "LT. ARIA VEGA",
    shipName: "SWIFT FANG",
    blurb: "Decorated squadron leader. Balanced in every theatre.",
    avatar: "/avatars/pilot-vega.png",
    // displayed on the select card, 1-5 scale
    stats: { SPD: 3, PWR: 3, SHD: 3, ROF: 3 },
    caps: {
      accel: 90,
      baseSpeed: 52,
      boostSpeed: 110,
      boostDrain: 28,
      fireRate: 0.14,
      laserDamage: 1,
      maxShield: 100,
      laserColor: 0x58ff9b,
    },
    ship: {
      hull: 0xe8eef5,
      dark: 0x2b3442,
      accent: 0xc81e3f,
      canopyGlow: 0x1899c2,
      glow: 0x7df5ff,
      bodyW: 1.0,
      noseL: 1.0,
      wingSpan: 1.0,
      style: "vega",
    },
  },
  {
    id: "hex",
    name: 'REX "HEX" VOLKOV',
    shipName: "NEEDLE NINE",
    blurb: "Ex-courier turned interceptor ace. Fast, loud, fragile.",
    avatar: "/avatars/pilot-hex.png",
    stats: { SPD: 5, PWR: 2, SHD: 2, ROF: 5 },
    caps: {
      accel: 112,
      baseSpeed: 62,
      boostSpeed: 134,
      boostDrain: 22,
      fireRate: 0.09,
      laserDamage: 1,
      maxShield: 70,
      laserColor: 0xffc24b,
    },
    ship: {
      hull: 0x3a4252,
      dark: 0x20262f,
      accent: 0xffa62b,
      canopyGlow: 0xff9a2b,
      glow: 0xffc24b,
      bodyW: 0.78,
      noseL: 1.4,
      wingSpan: 0.82,
      style: "hex",
    },
  },
  {
    id: "anvil",
    name: '"ANVIL" TARKA',
    shipName: "IRONCLAD",
    blurb: "Siege-breaker veteran. Slow to move, slower to die.",
    avatar: "/avatars/pilot-anvil.png",
    stats: { SPD: 2, PWR: 5, SHD: 5, ROF: 2 },
    caps: {
      accel: 70,
      baseSpeed: 46,
      boostSpeed: 96,
      boostDrain: 34,
      fireRate: 0.22,
      laserDamage: 2,
      maxShield: 150,
      laserColor: 0xbf7dff,
    },
    ship: {
      hull: 0x55706a,
      dark: 0x2c3a36,
      accent: 0xcd8a3c,
      canopyGlow: 0x9b59d0,
      glow: 0xbf7dff,
      bodyW: 1.3,
      noseL: 0.72,
      wingSpan: 1.22,
      style: "anvil",
    },
  },
];
